### PR TITLE
Change precedence in 'getResolvedState'

### PR DESCRIPTION
**Pull request by abbotteric**
* Previously existing props would overwrite passed in state
  * Now passed in state gets precedence

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I'm unsure of the implications of doing this.  It seems to be right, but this could affect a lot of internals.  Have you tested each story in the storybook thoroughly to ensure this will be okay?

**Comment by abbotteric** [comment]
I'll take a look through the storybook tonight and make sure it's covered. If I remember correctly the function only gets called with args in one other instance. Thanks for the feedback, I'll update with my findings soon.

**Comment by abbotteric** [comment]
From what I can tell, the only other call to getResolvedState() that passes arguments is in componentWillReceiveProps(). Line 39 in lifecycle.js accepts nextState as the 2nd argument. In this case nextState represents the React context which I don't believe ReactTable is currently setup to consume so nextState is always the Object prototype.

Currently the precedence goes: new props -> previous props -> context -> component state
This PR would change that to: new props -> context -> previous props -> component state

Since ReactTable doesn't use context right now, swapping it with previous props won't have any effect on current operation but I can see why some might want to keep it the way it is. If that's the case then the call to getResolvedState on line 65 of lifecycle.js would need to swap the order of arguments. That may come with other side effects that would still need to be investigated. Either approach would resolve #163 however.

FWIW I ran through the storybook and didn't run into any issues with the change in this PR. There aren't any stories for fully controlled components however. If I have some time I'll try to add one or two.

Thoughts?

**Comment by tannerlinsley** [comment]
If you could add a fully controlled story entry then I think we're good to
merge :)

**Comment by abbotteric** [comment]
Added a story entry with controlled sorting, page, and pageSize. Everything seems to be working as expected. If you were to revert commit 383554d2 you would see the behavior described in #163 and #145

**Comment by tannerlinsley** [comment]
Stupendous! You rock man. Merging this now.

**Pull request merged**
