### PR TITLE
setup size-plugin-bot

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**
Items:
- [x] Add rollup plugin `rollup-plugin-size`
- [x] Add configuration file(`.github/size-plugin.yml`) for [size-plugin 🤖](https://github.com/kuldeepkeshwar/size-plugin-bot)
- [x] Install [Github App](https://github.com/apps/size-plugin)  👈@tannerlinsley

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This was failing on the windows test, so I added a `cross-env` prefix. Could you pull this down and install `cross-env` as a dev dep?

**Comment by tannerlinsley** [comment]
Those sizes seem... off. Is it just me?

**Comment by tannerlinsley** [comment]
Screen Shot 2019-12-02 at 9 40 12 AM

**Comment by kuldeepkeshwar** [comment]
@tannerlinsley this `20.3 kB` is the gzipped size. The file is not minified. bundlephobia shows `11.2
kB` (MINIFIED + GZIPPED)

**Comment by stramel** [comment]
I think showing the minified + gzipped sizes would be more accurate to what we need. If I went in and added a bunch of code documentation, this would inaccurately reflect a large bump in size when in reality, none of that size is making it to the end user.

**Comment by tannerlinsley** [comment]
Yep. Minzipped.

Tanner Linsley

**Comment by kuldeepkeshwar** [comment]
@tannerlinsley @stramel that makes sense. currently, it is limited to `gzipped/brotli` size. 

We do have plans to add more flexibility to how sizes are calculated.

just to give a glance of how it may look like
```
    file ⏤  brotli  gzip   uncompressed 
index.js ⏤  20kB    25kB    80 kB

```

**Pull request merged**
