### PR TITLE
Added index.d.ts to the package.json

### PR DESCRIPTION
**Pull request by kizu**
Oops, forgot to put the definition file into the list of included files inside a package :)

### CODE REVIEW

**Comment by stramel** [comment]
Thanks for the PR but v6 type definitions are hosted on DefinitelyTyped and v7 type definitions are not quite ready yet.

**Comment by kizu** [comment]
This is a follow-up to the #1584 

TL;DR: if we'd like to have both v6 and v7 in one app during the migration process, we would need to have one of them renamed to something else, and in this case the typings for it won't be taken from the DefinitlyTyped, so if we would have a separate package for the v6, it would be much more convenient to have them alongside the code.

**Comment by kizu** [comment]
@tannerlinsley Hey, hope you got a good vacation :) Do you have an ETA for looking at this PR and the issue with publishing of v6 I've mentioned in https://spectrum.chat/react-table/general/additional-package-just-for-the-v7~7115661c-7e60-4a61-a16f-4be7e6796349

Not in hurry, but it would be nice to know the ETA so we could plan things (we really want to start using the v7!)

**Comment by tannerlinsley** [comment]
Got back from vacay a day or two ago. Still getting back up to speed, so a release is coming soon on the v6 parallel to v7 issue.

**Comment by kizu** [comment]
@tannerlinsley I have noticed the https://www.npmjs.com/package/react-table-v6, but it seems that it was published not by you, but by someone else, hmm. Do you know who they are?

**Comment by tklarryonline** [comment]
Thanks @kizu for your package. The https://www.npmjs.com/package/react-table-v6 does miss the `index.d.ts` file so it seems to be published before your PR.

**Pull request merged**
