### PR TITLE
feat(useGridLayout): Add functionality for proposed useGridLayout

### PR DESCRIPTION
**Pull request by CodyMoore240**
Add functionality for a new hook called `useGridLayout`. Other Layout hooks require the layout to be driven by the individual cells and row wrappers. This hook allows for a more stripped down markup and lets the top level div control the layout while still allowing individual cells and headerCells to control themselves. This works with `useResizeColumns` while not editing the `useResizeColumns` hook itself.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Why exactly does there need to be new table state to support the grid layout?

**Comment by CodyMoore240** [comment]
In its purest form there is no need for new table state since the grid layout just uses less HTML and allows CSS Grid to control the cell sizing. However, I had a need for column resizing and could not find a way to control the column widths without using state.

**Comment by tannerlinsley** [comment]
Did you end up requiring more than the existing resizing state offered?

**Comment by CodyMoore240** [comment]
I did as the grid layout needed to use a combination of `min-content` and `fr` units to make the resizing work as expected. I had to change the `grid-template-columns` property on the container based on the desired sizing of the columns. I used the `init`, `columnStartResizing`, `columnResizing`, and `columnDoneResizing` actions to make changes to a value in state called `gridLayout`. 

I will update the PR today to reflect the tweaks I have made along with a nicer looking example.

**Comment by tannerlinsley** [comment]
Okay. If you would also like to look into porting this to the next branch, that would be awesome.

Tanner Linsley

**Comment by CodyMoore240** [comment]
> 
> Okay. If you would also like to look into porting this to the next branch, that would be awesome. Tanner Linsley
> […](#)
> On Aug 4, 2020, 7:58 AM -0600, Cody Moore ***@***.***>, wrote: I did as the grid layout needed to use a combination of min-content and fr units to make the resizing work as expected. I had to change the grid-template-columns property on the container based on the desired sizing of the columns. I used the init, columnStartResizing, columnResizing, and columnDoneResizing actions to make changes to a value in state called gridLayout. I will update the PR today to reflect the tweaks I have made along with a nicer looking example. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Certainly. Will do. Thanks for the review.

**Comment by FezVrasta** [comment]
Hi, thanks for this new layout! I was wondering if this could solve the issue described in #1639? (having the table never exceed its parent width)

**Comment by CodyMoore240** [comment]
No problem. I hope you enjoy it. It certainly could solve the problem using some of the techniques laid out here https://css-tricks.com/snippets/css/complete-guide-grid/ but I believe you would have to play with the CSS overflow property to get it to work on small viewports.

**Comment by FezVrasta** [comment]
I think what it'd need is some logic that takes the column widths and adjusts them to not exceed the parent width.

Probably CSS grid can't help that much in this case. :-(

**Comment by utkarshgupta137** [comment]
This hook isn't visible in the docs. Am I missing something?

**Comment by xy2iii** [comment]
Although it's not present in the docs, it's usable in react-table at the time of this writing. You can still read the docs in `md` at [docs/api/useGridLayout.md](https://github.com/tannerlinsley/react-table/blob/master/docs/src/pages/docs/api/useGridLayout.md).

**Comment by casimcdaniels** [comment]
Is there an example? Just dropped it in doesn't work so I'm assuming I need to modify some of the rendering code.

**Comment by utkarshgupta137** [comment]
@casimcdaniels Refer to [this](https://github.com/utkarshgupta137/youtube-playlist-manager/commit/1df137bb85b8cc996ba7fb69328067ab362c459c#diff-35af2b09a4dc9d733c7d6823d4ca457897eb7f70d528f39748e1509775a76910) commit. I've moved from Material-UI rendering to useGridLayout rendering.

**Comment by CodyMoore240** [comment]
I think this was not supposed to be merged in to master. When I originally submitted the PR, @tannerlinsley went over it with me and think I recall him saying this would be good for the next version with some changes. I was surprised, and a little proud honestly, that this got merged into a release. If I did something wrong I apologize. 

I mainly use this to make it so I can flatten my table content with no wrapper elements while still making it scrollable. It is easy to control the table if all the content is just elements within a single parent. This allows you to keep the header cells the same width as their corresponding column cells as well as having a visually appealing fixed header in a scrollable container. Its really just a few lines of CSS so making this your own would be fairly easy.

It is good to see people getting some use out of it and I hope it meets your needs. As for it not being in the docs I assume it is because it was not intended to be in the release.

**Comment by utkarshgupta137** [comment]
Hey @CodyMoore240, I would say that GridLayout is way better than everything else I've tried for rendering. The auto-sizing of columns by content really makes everything easier especially when using groupBy or filters.
I think if this is included in the docs, a lot more people could make use out of it.

I've also created 2 PRs for improving it:
- https://github.com/tannerlinsley/react-table/pull/2994
- https://github.com/tannerlinsley/react-table/pull/2996
They're in the failed state due to some Vercel related bug, but otherwise good to go.

**Comment by casimcdaniels** [comment]
Thanks @utkarshgupta137  Here's a working example:

```tsx
const Styles = styled.div`
  padding: 1rem;
  width: 100%;

  .table {
    color: black;
    border: 1px solid gray;
    background: white;
    grid-gap: 1px;

    overflow: auto;
  }

  .table .header,
  .table .cell {
    padding: 0.5rem;

    background-color: white;
  }

  div table .header {
    font-weight: 700;
  }

  .table .cell {
    font-weight: 500;
    padding: 12px;

    &.even {
      background-color: hsl(0, 0%, 96%);
    }
  }
`;

export const SimpleTable = ({ columns, data }: any) => {
  const { getTableProps, headerGroups, rows, prepareRow } = useTable(
    {
      columns,
      data,
    },
    useResizeColumns,
    useGridLayout,
  );

  return (
    <Styles>
      <div {...getTableProps()} className="table">
        {headerGroups.map((headerGroup) => {
          return headerGroup.headers.map((column) => {
            return (
              <div {...column.getHeaderProps()} className="header">
                {column.render('Header')}
              </div>
            );
          });
        })}
        {rows.map((row, i) => {
          prepareRow(row);
          return row.cells.map((cell) => {
            return (
              <div {...cell.getCellProps()} className={`cell ${i % 2 === 0 ? 'even' : 'odd'}`}>
                {cell.render('Cell')}
              </div>
            );
          });
        })}
      </div>
    </Styles>
  );
};
```

**Comment by casimcdaniels** [comment]
I also agree with the sentiment, with GridLayout it just works but with the flexLayout is incredibly buggy and I cannot get overflow scrolling to work at all

**Comment by VercammenJens** [comment]
Hi, I'm trying to use the useGridLayout hook in my react/typescript application using react v17 and react-table v7.7.0. Is there any special import I should be aware of to use the useGridLayout? Because my react-table does not have a exported member 'useGridLayout'.

import looks like this:
`import {
  useGlobalFilter, useFilters, useTable, usePagination, useRowSelect, useGridLayout,
} from 'react-table'`

And my instance looks like this:
`  const instance = useTable(
    {
      columns,
      data,
      initialState: {
        hiddenColumns: columns.map((col: any) => {
          if (col.show === false) return col.accessor || col.id
        }),
      },
    },
    useFilters,
    useGlobalFilter,
    usePagination,
    useRowSelect,
    useGridLayout,
  )`

It's my first time asking for help on a github repo, so if you need more info just ask and I'll provide. Thanks

**Comment by CodyMoore240** [comment]
> Hi, I'm trying to use the useGridLayout hook in my react/typescript application using react v17 and react-table v7.7.0. Is there any special import I should be aware of to use the useGridLayout? Because my react-table does not have a exported member 'useGridLayout'.
> 
> import looks like this:
> `import { useGlobalFilter, useFilters, useTable, usePagination, useRowSelect, useGridLayout, } from 'react-table'`
> 
> And my instance looks like this:
> ` const instance = useTable( { columns, data, initialState: { hiddenColumns: columns.map((col: any) => { if (col.show === false) return col.accessor || col.id }), }, }, useFilters, useGlobalFilter, usePagination, useRowSelect, useGridLayout, )`
> 
> It's my first time asking for help on a github repo, so if you need more info just ask and I'll provide. Thanks

Hi @VercammenJens,

As far as I know this hook has not been tested with react v17 so it may not be compatible. This hook sort of got lost in the shuffle and was not ready to be merged into this repo. My apologies. If I have some time I will get it updated. Feel free to put an issue in and maybe someone from the community will take it. 

Sorry I cant be more help. Good luck!

**Comment by utkarshgupta137** [comment]
> Hi, I'm trying to use the useGridLayout hook in my react/typescript application using react v17 and react-table v7.7.0. Is there any special import I should be aware of to use the useGridLayout? Because my react-table does not have a exported member 'useGridLayout'.
> 
> import looks like this:
> `import { useGlobalFilter, useFilters, useTable, usePagination, useRowSelect, useGridLayout, } from 'react-table'`
> 
> And my instance looks like this:
> ` const instance = useTable( { columns, data, initialState: { hiddenColumns: columns.map((col: any) => { if (col.show === false) return col.accessor || col.id }), }, }, useFilters, useGlobalFilter, usePagination, useRowSelect, useGridLayout, )`
> 
> It's my first time asking for help on a github repo, so if you need more info just ask and I'll provide. Thanks

I'm able to import just fine using react v17.0.1 & react-table 7.6.3. You can refer to [this](https://github.com/utkarshgupta137/youtube-playlist-manager/commit/1df137bb85b8cc996ba7fb69328067ab362c459c#diff-35af2b09a4dc9d733c7d6823d4ca457897eb7f70d528f39748e1509775a76910) commit for a working example.

**Comment by VercammenJens** [comment]
@CodyMoore240 @utkarshgupta137 Thanks for the quick replies!

@utkarshgupta137 I've downgraded to v7.6.3 but still can't seem to import the useGridLayout. Odd. Might be a typescript thing then.

**Comment by Joyfred** [comment]
Please add this wonderful update in the docs. Took around an hour of googling to find this feature

**Comment by CodyMoore240** [comment]
@tannerlinsley any idea why useGridLayout is not showing up in the docs? I submitted a docs page along with this PR but it seems only the code made it in. Any help would be appreciated. Happy to submit the docs again.

**Comment by CodyMoore240** [comment]
> Hey @CodyMoore240, I would say that GridLayout is way better than everything else I've tried for rendering. The auto-sizing of columns by content really makes everything easier especially when using groupBy or filters. I think if this is included in the docs, a lot more people could make use out of it.
> 
> I've also created 2 PRs for improving it: #2994, #2996 They're in the failed state due to some Vercel related bug, but otherwise good to go.

Hey this is a really cool addition. Any word from Tanner on these?

**Comment by Joyfred** [comment]
@CodyMoore240 Setting minWidth to column options doesn't work. Is it something expected?

**Comment by utkarshgupta137** [comment]
@Joyfred I've raised a PR for this: https://github.com/tannerlinsley/react-table/pull/2994

**Comment by CodyMoore240** [comment]
> @Joyfred I've raised a PR for this: #2994

I think things like this are why Tanner initially said this was not ready for merge. There are most likely a few situations where this does not work as expected. Also usage with some of the plugin hooks may not have any effect. @utkarshgupta137 do you think we should make a fork of this with your changes merged in and note it here?

**Comment by utkarshgupta137** [comment]
Let's give @tannerlinsley a couple of weeks. If we suggests not merging this, then we can start a fork.

**Comment by tannerlinsley** [comment]
The main reason for delay is:
- been working on react location
- Been working on react query v4 + course
- Been working on react table v8 for Typescript rewrite

The plan is for Q1 of 2022 to be dedicated to React Table

**Comment by utkarshgupta137** [comment]
May I help you start working on getting back on it?

**Comment by austincondiff** [comment]
Do we have an example sandbox of `useGridLayout` in use? Looks like it may be a good fit for my use case as `useFlexLayout` paired with column resizing is causing big performance issues during resize even with virtualization. Recalcualculating each cells width in a flex row on every mouse movement while resizing is a pretty costly operation for the browser to handle.

**Comment by austincondiff** [comment]
Also, will this work with column groups? When I attempt to use useGridLayout with two groups for example, `grid-template-columns:  auto auto;` us put on the table which only gives me as many columns as there are groups. I got rid of the groups and because I was adding a selection column after the fact, it wasn't taking that into account rendered one less column than it should have. This seems like it needs a little love before being production-ready.

**Comment by CollinsSpencer** [comment]
> Also, will this work with column groups?

@austincondiff  I had previously posted a PR that fixes `useGridLayout` to work with column groups and column resizing.   https://github.com/TanStack/react-table/pull/3542 The PR was just closed as stale, but if you need `useGridLayout` in v7, you can always copy just the one hook into your project.

**Pull request merged**
