### PR TITLE
Pass defaults via props into useTable state

### PR DESCRIPTION
**Pull request by berdyshev**
This will allow to override any defaults for the table state (like `pageSize` for example)

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This doesn't quite cover the use case of hoisting the state out yourself for control. Take a look at the server-side rendering example in the code sandbox. 

Using `useTableState()` in your own code and passing to to the `useTable` hook is a necessary point of inversion of control to the user.

**Comment by tannerlinsley** [comment]
I'm not sure why you wouldn't just do this:

```javascript
const state = useTableState(defaults)

....
const table = useTable({ state })
```

**Comment by berdyshev** [comment]
I renamed it to `defaults` to make more self-explanatory, but I missed SSR point. So possible it makes sense to return back to the `state` name. But...
In response to the second question: I cannot use `useTable({ state })` because this requires to pass the complete state, which is not a good option when you need to just change only particular default value (e.g. `pageSize` in my first comment)

**Comment by tannerlinsley** [comment]
This should still be sufficient and extremely easy:

```javascript
const state = useTableState({ pageSize: 10 })
const table = useTable({ state })
```

**Comment by berdyshev** [comment]
ok, agree. should be sufficient.

**Pull request closed without merging**
