### PR TITLE
Sub rows are selected if the parent row is selected.

### PR DESCRIPTION
**Pull request by Codar97**
Selecting a row that has subRows will now also select the subRows. It makes sense to select subRows if the parent row is selected but this functionality may not be desired for react-table.

Parent rows are also updated according to the subRows selection.

Let me know if any optimisations can be made.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This looks good to me. If possible, could you update the snapshot test for the useSelectRows hook to utilize this code?

**Comment by Codar97** [comment]
Yeah, update it to test the added functionality.

**Comment by Codar97** [comment]
Rebased onto master to resolve conflicts.
Updated the snapshot test for useRowSelect.

The snapshots now additionally test the following:
- A row with two subRows is selected (Snapshot 3)
- A row with two subRows is deselected (Snapshot 4)
- One of two subRows is selected (Snapshot 5)
- Both of the subRows is selected (Snapshot 6)
- One of the subrows is deselected (Snapshot 7)

This should cover the added functionality checking that the parent row updates the subRows and the subRows update the parent rows accordingly.

**Comment by tannerlinsley** [comment]
Fantastic

**Pull request merged**
