### PR TITLE
Enhanced expander and pivot

### PR DESCRIPTION
**Pull request by TacticalCoding**
Enhance the `expander` column option to support most column features for Expander Columns and Pivot Columns.

Allows full control over positioning and rendering Expander Columns and Pivot Columns.

Update `Custom Expander Position` story.
Add `Pivoting Options` story.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This all looks amazing :) You rock man.

**Comment by tannerlinsley** [comment]
You let me know when you're good to merge.  I am ready when you are.

**Comment by TacticalCoding** [comment]
I'm ready. The demos all look like they're still working.

**Comment by tannerlinsley** [comment]
Awesome.  So would you say minor or major semver bump?

**Comment by TacticalCoding** [comment]
Hmm. I think the only breaking change is people using the `expanderColumnWidth`. I don't know your strategies for versioning. For me a minor change is fine.

**Comment by tannerlinsley** [comment]
Well, since the implementation of `expanderColumnWidth` was technically broken anyway, I can justify a minor bump. :)

**Pull request merged**
