### PR TITLE
Better support for subcomponents

### PR DESCRIPTION
**Pull request by manuxio**
I think this is a good start,
probably there should be a better way to pass more useful properties (check TdComponent ...)
Thank you!

### CODE REVIEW

**Comment by manuxio** [comment]
Hi, I'll give it a deeper look...
meanwhile, it would help me a lot to have a linter for your project... isn't there any?
I mean, some eslint configuration?

**Comment by tannerlinsley** [comment]
Standard.js is a dev dependency. Just npm run standard. You could also
install the standard linter plugin for your ide

**Comment by tannerlinsley** [comment]
Did that linter work for you @manuxio ?

**Comment by manuxio** [comment]
Actually, not... 
npm ERR! missing script: standard


But that's no big deal... the point is that I have had very little time to check the PR ... will do it asap (but also found that I don't want to replicate all data... just the very important ones... so the first PR will not be very different from the next release... 
Just a few more lines and I'll be done...

**Comment by tannerlinsley** [comment]
Be sure to yarn or npm install to get standard. If its not there, it should
be a dev dep

**Comment by manuxio** [comment]
Did both... no help... as a matter of fact, the only lint I saw was by github when I made the PR...
Sorry, simply can't understand that :(

**Comment by tannerlinsley** [comment]
To Lint:
- Make sure the linter is installed by running `npm install`.  This will install all dev dependencies.
- Then run `npm run test`.  This will run the standard.js linter and print any warnings to fix
Optional:
- Install the standard.js linter for atom, sublime, or VScode, and you'll get linting right in your editor.

**Comment by tannerlinsley** [comment]
Still very interested in this.  If you want to keep running with this PR, feel free to reopen and we can keep working through it.

**Pull request closed without merging**
