### PR TITLE
ci: setup github actions continuous integration workflow

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Example test run https://github.com/ChristianMurphy/react-table/commit/392525d730fa17f5bb4c33482d4576bc52493ee5/checks

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This is neat. What's this for other than moving away from travis?

**Comment by ChristianMurphy** [comment]
Mainly it offers an alternative to Travis, with slightly faster build start times from Windows and MacOS.

In addition this tests using `npm` as the package manager while Travis currently tests with `yarn`.
Though based on https://github.com/tannerlinsley/react-table/pull/1559#issuecomment-540201116
Maybe this should be migrated to `yarn` as well.

**Comment by tannerlinsley** [comment]
I have no loyalty to Travis, so if we migrated yarn as well, then I would be down with that.

**Comment by ChristianMurphy** [comment]
Updated to use yarn, updated example test run https://github.com/ChristianMurphy/react-table/commit/c993d235081867380bee460e5f28770d500594a7/checks

**Comment by tannerlinsley** [comment]
Very nice! Could you add a Badge to the readme in place of the travis badge?

**Comment by ChristianMurphy** [comment]
Sure added

[GitHub Actions CI](https://github.com/tannerlinsley/react-table/actions)
[Travis CI](https://travis-ci.org/tannerlinsley/react-table)
[Bundlephobia](https://bundlephobia.com/result?p=react-table@next)
[NPM Package](https://npmjs.com/package/react-table)
[Join the community on Spectrum](https://spectrum.chat/react-table)
[GitHub Stars](https://github.com/tannerlinsley/react-table)
[Twitter Followers](https://twitter.com/tannerlinsley)

**Comment by tannerlinsley** [comment]
Now the only missing piece is to remove Travis!

**Comment by ChristianMurphy** [comment]
Done, removed travis ci badge and config file.

**Pull request merged**
