### PR TITLE
onTrClick

### PR DESCRIPTION
**Pull request by DimitryDushkin**
+ README fix

React "peerDep ..." commit is totally optional.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Great work! You're the man.

**Comment by DimitryDushkin** [comment]
@tannerlinsley thx, great component!

**Comment by tannerlinsley** [comment]
@DimitryDushkin Thanks! 

Curiously, are you using React-Table for Yandex?

**Comment by tannerlinsley** [comment]
BTW just cut a new release for you 👍

**Comment by DimitryDushkin** [comment]
@tannerlinsley no exactly for big Yandex (search), but for projects within its department — Yandex Data Factory — b2b machine-learning solutions spinoff.

Thank you for release. =)

**Pull request merged**
