### PR TITLE
ci: test cross platform

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Test on Node.js 10 and 12, long term release support versions.
Test on Linux, Mac, and Windows machines.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I'm not sure why this is failing. Can anyone tell?

**Comment by stramel** [comment]
@tannerlinsley Looks like `is-ci-cli` may have an issue with Windows?

**Comment by ChristianMurphy** [comment]
As far as I can tell, `is-ci-cli` has an issue where it is unable to detect travis ci for windows as a CI environment.
I've logged this upstream as https://github.com/watson/is-ci/issues/19

I could revert the windows part and keep the MacOS and Linux part for now to unblock this, if folks prefer.

**Comment by tannerlinsley** [comment]
👍

Tanner Linsley

**Comment by stramel** [comment]
I don't see how it wouldn't be detecting the TravisCI as a CI environment. `is-ci-cli` uses `is-ci` which uses `ci-info` of which everything seems correct. Including your PR passing on Windows for `is-ci`. If `is-ci-cli` was failing to detect the CI environment, it _should_ fallback to running `test:dev` script.

I put out a PR on `is-ci-cli` to use `cross-spawn` and throw any errors that try to silently fail. Hopefully this will catch it.

**Comment by stramel** [comment]
@ChristianMurphy Can you try v2.0.0 of `is-ci-cli`?

**Comment by ChristianMurphy** [comment]
Thanks @stramel, updated to `is-ci-cli` version 2

**Comment by ChristianMurphy** [comment]
Closing this in favor of #1578 
The issue doesn't appear on GitHub actions CI workflow or in local testing.
I suspect the issue may with with Travis CI Windows beta issue.

**Comment by stramel** [comment]
@ChristianMurphy You can fix the issue by adding this to the `.travis.yml`

```yml
env:
  global:
    - YARN_GPG=no
```

**Comment by stramel** [comment]
@ChristianMurphy I wrote out a travis file for the `is-ci-cli` lib. https://github.com/YellowKirby/is-ci-cli/pull/6/files

https://travis-ci.org/stramel/is-ci-cli/builds/595780320

**Comment by stramel** [comment]
@ChristianMurphy You might want to try removing the quotes around the script. I _think_ that is causing windows to fail.

**Comment by tannerlinsley** [comment]
I agree. I'm not even sure how the package-lock.json got in there TBH

**Pull request merged**
