### PR TITLE
Add minRows to list of available props

### PR DESCRIPTION
**Pull request by ldstein**
Hi, this is a feature suggestion to toggle the rendering of padded rows.

This PR adds a new prop `showPaddedRows`. It's useful if you want the height of the table to be determined by the number of visible, populated rows.

We found it a bit more performant than setting `style:{display:none}` on empty rows via `getTrProps` (particularly when iterating through small data sets with large defaultPageSizes).

Included is a story which demonstrates the behaviour of the prop.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I feel like this is unnecessary with the `minRows` prop, which you can set to `0`.  Does this achieve something different than that?

**Comment by ldstein** [comment]
Ha, too true! Looks like I missed that prop before venturing down this rabbit hole.

Suggest adding `minRows` to the props section of `readme.md`. It's currently not listed as one of the available props.

**Comment by tannerlinsley** [comment]
Submit a pr? ;)

**Comment by ldstein** [comment]
Updated this PR.

**Comment by tannerlinsley** [comment]
Putting this as a default prop makes things kinda wonky for me. I think the docs should be enough in their own

**Pull request merged**
