### PR TITLE
[WIP] useColumnPin

### PR DESCRIPTION
**Pull request by gargroh**
Added new react table hook for Column Pinning/Freezing. It supports pinning to right and left of table. 

Functionality illustration - column-pinning

### CODE REVIEW

**Comment by tonilxm** [comment]
Really love this feature... I hope it can make it on next release ❤️ 😍

**Comment by tannerlinsley** [comment]
Big question here is whether or not this is supported with grouped headers and how compatible is it with other plugins?

**Comment by gargroh** [comment]
Yeah, it supports grouped headers well, but i doubt about its interaction
with plugins such as useAbsoluteLayout...

**Comment by luis-carlos-campos** [comment]
This plugin looks really good...
@gargroh Is it working properly on Safari?
@tannerlinsley Would you recommend anything for freezing columns on current version?

**Comment by gargroh** [comment]
I am planning to have different layout option also, like three different tables so as to have different horizontal scrollbars for each segment(left, center, right) this may require some more time, lets see how it goes.

**Comment by sherbakov1** [comment]
@gargroh Great and useful feature! When are we going to see it live in production?

**Comment by tannerlinsley** [comment]
This feature is awesome, though in v8, it will be implemented a bit differently. I used the general concepts here to build the new version (that ended up entirely different in v8's improved plugin system). I'm going to close this PR since there won't be any forward compatibility when v8 goes live.

**Comment by luis-carlos-campos** [comment]
@tannerlinsley Are you tracking this feature somewhere else for V8 ?

**Comment by tannerlinsley** [comment]
No, but all it would take is this PR to be reopened, pointed at the next branch and refactored to use the new plugin system.

**Comment by tannerlinsley** [comment]
Sorry, got confused. This plugin is already implemented on the next branch. You can check it out here: https://github.com/tannerlinsley/react-table/blob/next/src/plugins/withColumnPinning.js

**Comment by luis-carlos-campos** [comment]
That's awesome.
Thanks @tannerlinsley

**Comment by amd-9** [comment]
> Sorry, got confused. This plugin is already implemented on the next branch. You can check it out here: https://github.com/tannerlinsley/react-table/blob/next/src/plugins/withColumnPinning.js

Seems that link not working anymore :( Sorry for bothering @tannerlinsley but is there any already implemented solution for column pining?

**Pull request closed without merging**
