### PR TITLE
Add an option to hide the pagination if there is no data

### PR DESCRIPTION
**Pull request by cdtinney**
This will take priority over the default showPagination prop. It is set to a default of 'true'.

It is demonstrated in a 'ShowPaginationNoData' story.

Relates to #130, #248. The latter had some valid reasons on why this behavior should not be the default, so I added it as an option.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
@aaronschwartz Thoughts?

**Comment by aaronschwartz** [comment]
Hmm I'm not sure if the property is a little confusing. You could technically just override the entire PaginationComponent to achieve the same thing. I know that is not as easy but I'm not sure how many people want this use case. It also feels like you could use the handlers to just take control of `showPagination` but I'm not sure if it is feasible or not.

I'm alright either way. Do you prefer `showPaginationNoData` or `hidePaginationWhenNoData`?

**Comment by tannerlinsley** [comment]
I still think it could be inferred without the property somehow

**Comment by tannerlinsley** [comment]
This is an edge case that still needs to be addressed, but I think we should be inferring the display of the NoData component instead of forcing the user to set it manually.  Let's explore some ways to do that :)

**Pull request closed without merging**
