### PR TITLE
Run rename-unsafe-lifecycles on v6 branch

### PR DESCRIPTION
**Pull request by nbar1**

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I'm not sure I can do this without doing a major semver release. This would break a lot of people as a minor or patch release

**Comment by nbar1** [comment]
No worries, as v6 won't be receiving any large changes in anticipation of v7, I will import it from my repo until we upgrade.

**Comment by tannerlinsley** [comment]
Sounds good. I think that's the best solution for now. Thanks!

**Comment by fttriquet** [comment]
Are you going to do a 6.11 version with this ? If so when is it planned ?

Thanks

**Comment by benflodge** [comment]
This fix has broken compatibility with Preact, as they are not supporting the UNSAFE* methods preactjs/preact#1047. I have fixed my react-table version to 6.10.0 as this version still works with Preact.

**Comment by benflodge** [comment]
There is a now a bug for Preact tracking the broken compatibility issue https://github.com/preactjs/preact/issues/1941.

**Comment by vis2992** [comment]
Seems like the preact issue is resolved now, could this PR be opened up again and released as a new major version?

**Pull request closed without merging**
