### PR TITLE
Fix bug in sortData subRows

### PR DESCRIPTION
**Pull request by leyinetwork**
Fix sort subRows stop recursion when subRows length is one.
If row.subRows length is one, the subRows of row.subRows[0] will not sort in recursion

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Why would you need to sort a single row?

**Comment by leyinetwork** [comment]
Because I want to sort subRows data in recursion. If I have data[n].subRows[0].subRows[0].subRows[0] data set and data[0].subRows length is one, I can't sort the data in data[n].subRows[0] and subRows of the data in data[n].subRows[0]

You can find the case in https://codesandbox.io/embed/boring-sanne-d56h1?fontsize=14&hidenavigation=1&theme=dark

**Comment by leyinetwork** [comment]
@tannerlinsley Can you take a look?

**Comment by tannerlinsley** [comment]
Ah. I see. Good find.

**Pull request merged**
